---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-nlu-korean
  namespace: chatbot
  labels:
    app: chatbot-nlu-korean
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-nlu-korean
  template:
    metadata:
      labels:
        app: chatbot-nlu-korean
    spec:
      containers:
        - command:
          - /bin/bash
          - -c
          - ./bp lang --offline --dim 300 --langDir ./data/embeddings/
          image: kitaeyoo777/korean-nlu:test1
          name: korean-nlu-server
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: http 
          resources:
            limits:
              cpu: 2000m
              memory: 20Gi
            requests:
              cpu: 1000m
              memory: 10Gi
          env:
            - name: PORT
              value: "4000"
            - name: BP_HOST
              value: "localhost"
            - name: BP_PRODUCTION
              value: "true"
            - name: EXTERNAL_URL
              value: http://localhost:4000
          volumeMounts:
          - mountPath: /botpress/data
            name: chatbot
      volumes:
      - name: chatbot
        persistentVolumeClaim:
          claimName: chatbot                
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatbot-nlu-korean
  name: chatbot-nlu-korean
  namespace: chatbot
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3100
  selector:
    app: chatbot-nlu-korean
  sessionAffinity: None
  type: NodePort
